### ISSUE TITLE
IndentationError in v1meta.py

### ISSUE THREAD

**Issue by ddraayer** [versionone/VersionOne.SDK.Python#34]
I am unable to import v1pysdk at all due to an indentation error:

```
>>> import v1pysdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "v1pysdk/__init__.py", line 10, in <module>
    from v1meta import V1Meta
  File "v1pysdk/v1meta.py", line 126
    update_doc.append(node)
                          ^
IndentationError: unindent does not match any outer indentation level
```
It appears there is an extra space on line 126 of v1meta.py that was introduced in [a commit on 2015-Sep-10](https://github.com/versionone/VersionOne.SDK.Python/commit/447e042584bf3bd424c1ff7a83fb247b9d299543) (likely due to the use of unconventional tabstop widths). This is a very blatant problem; is anyone else experiencing this?

**Comment by mtalexan** [comment]
Lots of forks of this unmaintained project have fixed this.  Here's one:
https://github.com/mtalexan/VersionOne.SDK.Python
